In [2]:
import numpy as np
t =np.arange( 101) ** 2
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
a = np.eye(4, 5)
print a
a[[0,3],[1,3]]

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]]


array([ 0.,  1.])

In [12]:
type(t)

numpy.ndarray

In [20]:
m[2 1]

SyntaxError: invalid syntax (<ipython-input-20-76dd504262a9>, line 1)

In [9]:
t[2][3]

IndexError: invalid index to scalar variable.